AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyTopic:
    Type: AWS::SNS::Topic
    Properties:
      KmsMasterKeyId: alias/aws/sns

  MyTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref MyTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowOnlySSL
            Effect: Deny
            Principal: "*"
            Action: "SNS:Publish"
            Resource: !Ref MyTopic
            Condition:
              Bool:
                aws:SecureTransport: false